### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by quocbahuynh** [sickdyd/react-search-autocomplete#102]
**Describe the bug**
I have received a bug when selecting the item.

**Comment by sickdyd** [comment]
Can you give more details about the issue?

How to reproduce it?

Can you make a codesandbox with an example, please?

**Comment by coder-raghu** [comment]
Add and check 
resultStringKeyName="title" // String to display in the results
Its working for me

**Comment by sickdyd** [comment]
Just to clarify for other users as well. By default `resultStringKeyName` is `name`, but if your items are a list such as (this objects do not have the `name` key):

```js
 const items = [
   {
     id: 0,
     title: 'Titanic',
     description: 'A movie about love'
   },
   {
     id: 1,
     title: 'Dead Poets Society',
     description: 'A movie about poetry and the meaning of life'
   }
 ]
```

You will need to use one of the 3 keys `id`, `title` or `description`. This will be the value displayed in the results. If you try to use a key that does not exist, the error will appear. I will try to make a better descriptive error.
