### ISSUE TITLE
blur event should close dropdown

### ISSUE THREAD

**Issue by lkretzschmar** [sickdyd/react-search-autocomplete#106]
When I type something in the inputbox, teh dropdown appears. If I then Tab to the next element, the dropdown does not close.

This is reproducible on the demo page:

1. Go to https://sickdyd.github.io/react-search-autocomplete/
2. Click on the square input box by the Titanic prompt.
3. Type abc
4. See dropdown appear
5. Press Tab key
6. See dropdown stay open

**Expected behavior**
Expect dropdown to close when input field loses focus.

**Comment by sickdyd** [comment]
@lkretzschmar Fixed in the latest version!
