### ISSUE TITLE
Blue Border of inner Text Field

### ISSUE THREAD

**Issue by felixele217** [sickdyd/react-search-autocomplete#108]
**Describe the bug**
Hey guys, unfortunately we are encountering a blue inner border after clicking the text field on the search bar.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/50794814/230051736-af781ea5-bd6a-4aa6-84f2-f9c82bce5bdd.png">

The problem occured after we updated MUI. These are our dependencies:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/50794814/230052006-b4d48fc2-475a-44ea-b07e-9d885d2f557c.png">
<img width="340" alt="image" src="https://user-images.githubusercontent.com/50794814/230052337-fb409a47-44ee-4dce-928e-5d1d622bbde0.png">

And this is the code:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/50794814/230052171-8bdd9974-0568-42aa-9cc3-de154afdba6d.png">

Greetings Felix

**Comment by devp4** [comment]
Have you found a fix for this?

**Comment by sharkfabri** [comment]
I had the same issue using Tailwind CSS.
Solved adding:
```
input:focus {
  box-shadow: none !important;
}
```

**Comment by sickdyd** [comment]
@sharkfabri Thank you for posting this. I tried to reproduce the issue but was unable to. If this fix works well, just use that. If you want me to investigate this further please provide a codesandbox with the issue. Btw, which browser?

**Comment by sharkfabri** [comment]
> @sharkfabri Thank you for posting this. I tried to reproduce the issue but was unable to. If this fix works well, just use that. If you want me to investigate this further please provide a codesandbox with the issue. Btw, which browser?

Thank you @sickdyd, I just fixed this way, thank you. FYI on all browsers (Chrome, Firefox, Edge...) added a blue border on input focus. I guess it's related to Tailwind because not including it the border disappeares. Anyway that simple CSS fixes the bug.

<img width="370" alt="Screenshot 2023-07-17 alle 08 43 11" src="https://github.com/sickdyd/react-search-autocomplete/assets/60701536/e4474412-01b4-44c7-bfeb-895fb23e9812">

**Comment by felixele217** [comment]
my fix for this was this:

in app.css

```
[type='text']:focus {
    @apply ring-transparent;
}
```
