### ISSUE TITLE
Remove additional search icons from dropdown

### ISSUE THREAD

**Issue by keaton4422** [sickdyd/react-search-autocomplete#119]
Is it possible to only have the search-icon on the top of the search, but not in the results? I have been trying to hide the additional search-icons with no luck

**Comment by keaton4422** [comment]
I figured it out, in global.css put 

.wrapper > div:not(:first-child) .search-icon {
  display: none;
}

**Comment by adiyat-shihab** [comment]
it's basically work with  `showIcon={false}` props
