### ISSUE TITLE
Multiple warnings on react component

### ISSUE THREAD

**Issue by notleanbarba** [sickdyd/react-search-autocomplete#121]
**Describe the bug**
When sending the form, console logs multiple warning regarding <input> tag on search bar. 

**Codesandbox example**
https://codesandbox.io/p/sandbox/busy-hooks-9kfmct

**To Reproduce**
1. Enter "John" in search box
2. Select any result
3. See error in console and window

**Expected behavior**
No React warnings is expected

**Screenshots**
![image](https://github.com/sickdyd/react-search-autocomplete/assets/35031625/7f7d75a2-076e-4adf-ae0d-3f362f539de2)

**Additional context**
using "react": ">=16.0.0"

**Comment by YusufCelik** [comment]
I have the same issue! I cannot for the life of me understand why this suddenly happened. As the OG reports, it happens when you just select a result!

**Comment by YusufCelik** [comment]
Ok, I found the issue. 

@notleanbarba, you *need* to have a name prop. 

```    
fuseOptions={{
    keys: [
      "customer_name",
      "hot_tub_id",
      "technician_name", // -> name
      "servicetime",
    ],
}}
 
 
 In my case it was changing resultStringKeyName...

**Comment by notleanbarba** [comment]
That works. Good catch!

_Edit:_ 

**Error strings (For google search)** 
- "Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component."
- "ReactSearchAutocomplete.js:155 Uncaught TypeError: Cannot read properties of undefined (reading 'length')"
- "The above error occurred in the <ReactSearchAutocomplete> component:"

**Possible improvement**
This issue report should be enough to document the warning. However, a try-catch could be added to handle this.

**Comment by jarrodwhitley** [comment]
To clarify, I had to add a new property to the component 

``` javascript
<ReactSearchAutocomplete
                items={products}
                onSearch={handleOnSearch}
                onSelect={handleOnSelect}
                fuseOptions={{ keys: ['title', 'tags', 'brand'] }}
                resultStringKeyName="title"
            />

```
