### ISSUE TITLE
clearable icon for search input

### ISSUE THREAD

**Issue by SandhyaLingolu** [sickdyd/react-search-autocomplete#15]
Do we have option to show or hide clearable cross icon for search input ?

**Comment by sickdyd** [comment]
Hello @SandhyaLingolu!

I added the feature in the version `5.1.0`, checkout the demo to see it in action: https://sickdyd.github.io/react-search-autocomplete/

**Comment by sickdyd** [comment]
Close because solved in version 5.1.0
