### ISSUE TITLE
placeholderColor cannot be changed

### ISSUE THREAD

**Issue by kevingoenadibrata** [sickdyd/react-search-autocomplete#16]
I saw in the docs that the default value for placeholderColor is set to 'grey'. I wanted to change the color of the placeholder so I added a prop to the component. I added this code in `styling={{placeholderColor: "#ffffff"}}`
and apparently, it is still showing a grey color for the placeholder.

**Comment by sickdyd** [comment]
@kevingoenadibrata Hello! I fixed the issue in the release `5.0.9`.

Checkout the sandbox with a working example: https://codesandbox.io/s/peaceful-voice-1ludg?file=/src/App.js

**Comment by kevingoenadibrata** [comment]
Awesome! Tried in my code, it works! Thanks
