### ISSUE TITLE
Setting value of searchInput or clear input field without clear icon

### ISSUE THREAD

**Issue by lindaerin** [sickdyd/react-search-autocomplete#20]
How can I manually set the value of the searchInput field with inputSearchString? I have a placeholder value and onSelect event handler but want to clear input field when my onChange handler for my dropdown component is fired. It is not letting me do that with inputSearchString.  I essentially want to be able to clear the input field without pressing the clear icon

**Comment by sickdyd** [comment]
@lindaerin Hello!

You might want to take a look at this issue: https://github.com/sickdyd/react-search-autocomplete/issues/17

Codesandbox: https://codesandbox.io/s/distracted-fermat-zo6r8?file=/src/App.js

Let me know if it fixes your problem.
