### ISSUE TITLE
Clearing Text on firing onSelect Event

### ISSUE THREAD

**Issue by rohail111** [sickdyd/react-search-autocomplete#23]
1. I want to clear my input text automatically when I select a value from the dropdown.
2. Is there any way to give reference to this component or can we get the data by giving it Id and then get it by document.getElementbyId event? 
Kindly help I am stuck in it.

**Comment by sickdyd** [comment]
@rohail111 Hello!

You might want to take a look at this issue: https://github.com/sickdyd/react-search-autocomplete/issues/17

Codesandbox: https://codesandbox.io/s/distracted-fermat-zo6r8?file=/src/App.js

Let me know if it fixes your problem.

**Comment by sank2000** [comment]
> @rohail111 Hello!
> 
> You might want to take a look at this issue: #17
> 
> Codesandbox: https://codesandbox.io/s/distracted-fermat-zo6r8?file=/src/App.js
> 
> Let me know if it fixes your problem.

it fixed my issue

**Comment by sickdyd** [comment]
Close because fixed 🚀
