### ISSUE TITLE
How can set default value in autocomplete ? 

### ISSUE THREAD

**Issue by alamtopan** [sickdyd/react-search-autocomplete#24]
How can set default value in autocomplete ? 

on collection data 
data = [
 {id: 0, name: 'alam'},
 {id: 1, name: 'edit'},
 {id: 3 name: 'asa'}
]

i want set default, with id = 0 or name alam ? its posible or not without selected first.

**Comment by sickdyd** [comment]
@alamtopan Hello!

You might want to take a look at this issue: https://github.com/sickdyd/react-search-autocomplete/issues/17

Codesandbox: https://codesandbox.io/s/distracted-fermat-zo6r8?file=/src/App.js

Let me know if it fixes your problem.

**Comment by rughaanimskhan** [comment]
Hey @alamtopan,

Unable to set default value on load, can you please help me for this issue?

**Comment by bharath2612** [comment]
yes, how to set default value of input on load, please help :)

**Comment by sickdyd** [comment]
@rughaanimskhan @bharath2612 You can use the `inputSearchString` to set a default value:

```
<ReactSearchAutocomplete
 items={items}
 onSearch={handleOnSearch}
 inputSearchString="hello"
/>
```
