### ISSUE TITLE
how to set the search result to input background with silver color to suggest user complete it? like google drive search input

### ISSUE THREAD

**Issue by tahaamiri** [sickdyd/react-search-autocomplete#25]

**Comment by sickdyd** [comment]
Hello @tahaamiri,

if you look at the last example in the demo (with green colors) you can see that I set a green background. You can take a look at it to see how it works, but basically you just have to use the `styling` prop and pass `hoverBackgroundColor` with the color you want.

```
styling={{ hoverBackgroundColor: "silver" }}
```

**Comment by sickdyd** [comment]
Closing because solvable with `styling` prop
