### ISSUE TITLE
How to add Arrow key navigation to navigate to the results.

### ISSUE THREAD

**Issue by vividrizwan** [sickdyd/react-search-autocomplete#26]
How to add Arrow key navigation to navigate to the results.

**Comment by clasnake** [comment]
+1 same question here.

**Comment by sickdyd** [comment]
@vividrizwan @clasnake Hello!
I have not yet implemented this feature, so for now it's not possible to navigate with arrow keys.

I will add it to the list of features to implement.

Thanks for your feedback.

**Comment by sickdyd** [comment]
FYI: there's an open PR for this: https://github.com/sickdyd/react-search-autocomplete/pull/34

**Comment by Raza410** [comment]
Is this feature available now?

**Comment by sickdyd** [comment]
@vividrizwan @Raza410 RSA `v6.1.1` supports key navigation!
