### ISSUE TITLE
How to trigger onSearch event when emptying all the text in the search box?

### ISSUE THREAD

**Issue by clasnake** [sickdyd/react-search-autocomplete#27]
Currently looks like the onSearch callback is not triggered when emptying all the text by using backspace (instead of triggering the onClear) in the search box. Is it able to allow that to be configurable? Thanks.

**Comment by clasnake** [comment]
Found the onClear config. Close this issue. Thanks.

**Comment by sickdyd** [comment]
@clasnake Hello! Try to look into this issue if it helps: https://github.com/sickdyd/react-search-autocomplete/issues/17

Please let me know if not.

**Comment by sickdyd** [comment]
Closed because fixed ⭐
