### ISSUE TITLE
How to overlay a component result 'react-search-autocomplete' on top of another component's element?

### ISSUE THREAD

**Issue by taixe** [sickdyd/react-search-autocomplete#29]
Hi everybody?
How to overlay a component result 'react-search-autocomplete' on top of another component's element?
I get a error .
<img width="603" alt="Screen Shot 2021-08-09 at 09 55 20" src="https://user-images.githubusercontent.com/60805385/128656109-247da593-1151-4d9e-b93b-f888c37230f4.png">

**Comment by sickdyd** [comment]
Hello @taixe,

I think that the problems is related to the `z-index` of the image/component below. What you can do is use a higher `zIndex` for the search component by passing the `styling` prop with `zIndex`.

In the example below I'm using `9999` but it's possible that the component covering the search box has a higher value, so you might want to figure out what's that value or increase `zIndex` until it's covered. Let me know if this helps:

```
styling={{ zIndex: "9999" }}
```

**Comment by taixe** [comment]
Thank @sickdyd . The problems clear with zIndex.
