### ISSUE TITLE
Zindex error for this component

### ISSUE THREAD

**Issue by RuddyReisberg** [sickdyd/react-search-autocomplete#3]
Hello, 

I want to see myCompnentReactSearchAutocomplete in my front but it is blocked by an other.
Please, see the join.

Thanks you very much
![file2](https://user-images.githubusercontent.com/59610535/86936718-aa72ba00-c13e-11ea-8df0-8e41ccc52aac.png)
![file1](https://user-images.githubusercontent.com/59610535/86936720-ab0b5080-c13e-11ea-9131-115ea90a7543.png)

**Comment by sickdyd** [comment]
Hello RuddyReisberg,

apologies for the late reply. Could you provide an example on CodeSandBox or similar? https://codesandbox.io

The first thing I would try is to wrap the search boxes in a `<div>` with increasing z-index. Something like:

```
<div style={{ zIndex: 1 }}>
  <ReachSearchAutocomplete />
</div>

<div style={{ zIndex: 2 }}>
  <ReachSearchAutocomplete />
</div>
```

Let me know if this helps!

**Comment by raikk** [comment]
@sickdyd I have same issue here. Even I wrapped in div with zIndex 4, still can't. See this, please suggest where to make able to modify styling of this module??
<img width="674" alt="Screenshot 2022-05-03 at 9 32 35 PM" src="https://user-images.githubusercontent.com/12422925/166491725-c5b177ee-cdf8-4bf8-8d88-5fdd4beda0b9.png">

**Comment by raikk** [comment]
Ohh... got it. We have to use `styling` 

```
<ReactSearchAutocomplete
   styling={{backgroundColor: '#fff', 
zIndex: 2, 
placeholder: 'Type Country',
 placeholderColor: "#939294", 
borderRadius: "2px", 
height: "35px"}}   
...
/>
```

**Comment by sdodson99** [comment]
For anyone looking for a simple and dynamic solution to this, you can target the `.wrapper:focus-within` pseudo-element so that the results dropdown covers everything when the inner search input is focused:

```css
.wrapper:focus-within {
  z-index: 10;
}
```

I couldn't really hard-code the z-index for my use case because I have unlimited, conditional inputs.
