### ISSUE TITLE
Function formatResult only return one field, how to get full data from this

### ISSUE THREAD

**Issue by taixe** [sickdyd/react-search-autocomplete#30]
How to I can get full objet data  in this function. it only return item is name. I want to get  full data item = {name:"", image:"abc", etc...}
const formatResult = (item) => {
    return item; 
   // return (<p dangerouslySetInnerHTML={{__html: '<strong>'+item+'</strong>'}}></p>); //To format result as html
  }

**Comment by sickdyd** [comment]
@taixe For that you need to use `onSearch` and not `formatResult`. `onSearch` will return the full object, `formatResult` is used only to format the string in the results list.

**Comment by taixe** [comment]
hi @sickdyd . But I want to use formatResult to format data cell, show name, price, image ...

**Comment by sickdyd** [comment]
@taixe This can't be done now, but it seems easy to change. You can fork the repo and change this:

```
{formatResult(result[resultStringKeyName])}
```

to:
```
{formatResult(result)}
```

In `Results.js`, and you should get the full result in the callback.

**Comment by taixe** [comment]
yea, thank @sickdyd

**Comment by glowdex** [comment]
hi! I would like to do this too. I can fork and change as discussed above but I was wondering if it's possible to add it as an option for the function (whether you want the full results)?
