### ISSUE TITLE
How to detect empty input?

### ISSUE THREAD

**Issue by leoleung0102** [sickdyd/react-search-autocomplete#33]
Hello, I am using this library for handling autocomplete, but I would like to disable the search button when no input, but I find out when there is no input , it will not trigger handleOnSearch. Any solution? Thanks

**Comment by sickdyd** [comment]
@leoleung0102 Hello! Please take a look at[ this issue](https://github.com/sickdyd/react-search-autocomplete/issues/17), it seems that it was solved there. Let me know if it does not help.

**Comment by sickdyd** [comment]
Closed because of no reply and potentially solved in another issue.
