### ISSUE TITLE
How to show Message if related data not found

### ISSUE THREAD

**Issue by Chinmaypattar** [sickdyd/react-search-autocomplete#41]
How to show a error message like "No Data Found" ,when we didn't get the any value

**Comment by sickdyd** [comment]
@Chinmaypattar This sounds like a new feature. I'll try to add it when I have the time.

**Comment by sickdyd** [comment]
@Chinmaypattar I added the option in version `7.0.0`. It is enabled by default, so you can see it already in the demo version: https://sickdyd.github.io/react-search-autocomplete/

More info about the feature in the props section of the readme (the last entries).
