### ISSUE TITLE
Show list on click at input

### ISSUE THREAD

**Issue by bismarck4lves** [sickdyd/react-search-autocomplete#45]
In the Documentation, we have a variable items with the values that will be presented when typing.
Since we have these values, it would be interesting to show these preloaded values when clicking on the input. Is it possible to do that?

**Comment by PunkSage** [comment]
I don't think it is possible with the current code. I can fork this repository and think about it.

**Comment by sickdyd** [comment]
@bismarck4lves @PunkSage I added the feature in version `7.1.0`, to enable it you will need to pass this prop as true:

```
showItemsOnFocus={true}
```
