### ISSUE TITLE
ENTER key gives errror

### ISSUE THREAD

**Issue by beinoriusju** [sickdyd/react-search-autocomplete#57]
Without typing anything just focusing on component's input and hitting ENTER key gives me an error:

**TypeError: results[highlightedItem] is undefined**

Component should not assume results is non-emty array.

**Comment by alamgir8** [comment]
Hey, I just check with version @6.0.0, and it's working fine, not giving any error now!. I think the problem is with the latest version. You can check with this version : npm i react-search-autocomplete@6.0.0

**Comment by sickdyd** [comment]
@beinoriusju @alamgir8 Thanks for reporting this, I will look into it over the weekend.

**Comment by sickdyd** [comment]
@beinoriusju @alamgir8 This problem has been fixed in version `6.1.2`, please check it out!
