### ISSUE TITLE
README improvement - id is mandatory 

### ISSUE THREAD

**Issue by gofri** [sickdyd/react-search-autocomplete#61]
I recommend adding to the README that id is a mandatory field (otherwise there's a React bug due to key-field conflicts).
p.s. awesome gadget! easy to setup and works great

**Comment by sickdyd** [comment]
@gofri Thanks for reporting this. Added in this commit: https://github.com/sickdyd/react-search-autocomplete/commit/ffb1ee0017df6440e8acec602fc726f200bcd067
