### ISSUE TITLE
axios - autocomplete

### ISSUE THREAD

**Issue by redimongo** [sickdyd/react-search-autocomplete#62]
I am wondering how do I make the list be able to be from a axios request?

I found out the hard way that you can't do this
```js
 function checkAnswer(event, e) {
    
            if(currentTimeoutId){
                clearTimeout(currentTimeoutId);
             }
         
             currentTimeoutId = setTimeout(function(){
                 currentTimeoutId = null;
                    axios.get('https://nominatim.openstreetmap.org/search.php?city='+e+'&countrycodes=AU&featuretype=county&polygon_geojson=1&format=json')
                    .then(function (response) {
                    // handle success
                    //alert(JSON.stringify(response.data))
                    console.log(response);
                    document.getElementById("results").innerHTML = "";
                    for (let i = 0; i < response.data.length; i++) { 
                      //  alert(response.data[i].osm_id)
                        document.getElementById("results").innerHTML +="<button onClick={addToResult("+response.data[i].osm_id+")}>ID:"+response.data[i].osm_id+" - "+response.data[i].display_name+"</button>\n\n"
                    }
        
                    })
                    .catch(function (error) {
                    // handle error
                    console.log(error);
                    })
                    .then(function () {
                    // always executed
                    //alert(response)
                    });
                },1000);
        
        }
```

**Comment by sickdyd** [comment]
@redimongo Can you please make a codesandbox example?

**Comment by enesmozer** [comment]
I have faced the similar issue. I want to send request to an api when input value change but i couldnt find any onChange event. Is there any way to search with async data ?

**Comment by sickdyd** [comment]
@redimongo @enesmozer 

I think what you guys want to do is resolved in this comment: https://github.com/sickdyd/react-search-autocomplete/issues/50

I'll close this for now, but if you have still problems please create a codesandbox example.

> @yanffz Hello! All you need to do is to add a handler for `onSearch` where you use something like `fetch` to send the request to the API and then pass the new items to RSA. A rough example:
> 
> ```
>   const [items, setItems] = useState([])
> 
>   const handleOnSearch = async (string, results) => {
>     await fetch(`api/endopoint?search=${string}`)
>       .then(response => response.json())
>       .then(data => setItems(data))
>   }
> 
>   // in the render method
>   <ReactSearchAutocomplete
>     items={items}
>     onSearch={handleOnSearch}
>   />
> ```
> 
> Said that, what does the first API call do? Is it searching for a string? If so, you are basically sending a search query to an endpoint, getting some results, putting them in RSA then searching again within RSA; it's a bit weird. Ideally RSA should have a single list that needs to be searched in. I think that what you need is just a normal `select` element that shows the list of items you get from the API.

**Comment by terrylinooo** [comment]
```
const [items, setItems] = useState([])

  const handleOnSearch = async (string, results) => {
    await fetch(`api/endopoint?search=${string}`)
      .then(response => response.json())
      .then(data => setItems(data))
  }

  // in the render method
  <ReactSearchAutocomplete
    items={items}
    onSearch={handleOnSearch}
  />
```
This code actually doesn't work because it shows the result before fetching the API response. We have to press space key to get the updated results. Is there callback function we can manually show the dropdown list?

**Comment by thanhvdt** [comment]
@sickdyd Can you resolve this issue?

**Comment by raphaelbeckmann** [comment]
@terrylinooo @thanhvdt @sickdyd 

I managed that to work by setting at least one "dummy" item in the default list:
```
const [items, setItems] = useState([{ name: 'Searching...' }])
```

Additionally, you should increase the input debounce time to 500ms to reduce unnecessary queries to your server.
And, most important, you should set the [threshold to 1 in the fuseOptions prop](https://www.fusejs.io/api/options.html#threshold) to match all search results coming from the server.
```
<ReactSearchAutocomplete
    items={items}
    onSearch={handleOnSearch}
    inputDebounce={500}
    fuseOptions={{
        threshold: 1,
        keys: ['name', 'description'],
    }}
/>
```

Thereby, after having entered the search string the result box will initially show the default state value "Searching..." and then the results from the server.

You should also consider resetting the items back to the default state value if the input string is too short:

```
const handleOnSearch = async (string, results) => {
    if (string.length < 2) {
        setItems([{ name: 'Searching...' }]);
    }
    else {
        await fetch(`api/endopoint?search=${string}`)
            .then(response => response.json())
            .then(data => setItems(data))
    }
}
```
