### ISSUE TITLE
Search results dropdown is transparent

### ISSUE THREAD

**Issue by KishoreKumar18** [sickdyd/react-search-autocomplete#63]
Is there a way where we can set the background color, height, width for the Search results container? In my code, the background of the dropdown container is transparent. Hence, I could see the below fields overlapping with the dropdown. I was able to set the styling for each items using formatResult prop but could not handle the container. Also, wondering whether the zIndex might have something to with the overlapping.
<img width="175" alt="autocompletedropdown" src="https://user-images.githubusercontent.com/93245264/168826047-c9d9a350-816b-4927-bee3-a142dcfddc34.png">

**Comment by sickdyd** [comment]
@KishoreKumar18 It looks like there's some problem with the z-index. Could you provide a codesandbox example with the issue? It would make it easier to try to fix.

**Comment by sickdyd** [comment]
Closing because I assume that the `zIndex` change fixed the problem.
