### ISSUE TITLE
handleOnSearch is unclear

### ISSUE THREAD

**Issue by OmniscienceAcademy** [sickdyd/react-search-autocomplete#67]
handleOnSearch is unclear. We do not understand what the result parameter is used for

    // onSearch will have as the first callback parameter
    // the string searched and for the second the results. <-- What does this mean? 

I do not understand what you mean by results. Thanks

**Comment by sickdyd** [comment]
@OmniscienceAcademy `onSearch` is called every time you type text. Every time you type there are potential `results`, those are returned along with the string searched. It could be an empty array if there are no results from the string searched. Let me know if this helps.

**Comment by sickdyd** [comment]
I hope the above answer resolves the issue. I will close this for now.
