### ISSUE TITLE
Library seems not supported to be used in ts project, no declaration module.

### ISSUE THREAD

**Issue by fidellr** [sickdyd/react-search-autocomplete#69]
**Describe the bug**
Not supporting ts project, no declaration module was provided by the library, and block development to use inside ts project

**Codesandbox example**
Create a [codesandbox](https://codesandbox.io/) example with the problem you would like to have solved.

**To Reproduce**
1. Install library with yarn
2. Import inside tsx file
3. See error ```Could not find a declaration file for module 'react-search-autocomplete'. 'E:/xxx/node_modules/react-search-autocomplete/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-search-autocomplete` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-search-autocomplete';```

**Expected behavior**
Suppport to be use in ts project

**Comment by gignupg** [comment]
Same issue here!

**Comment by sickdyd** [comment]
@fidellr Thank you for reporting this issue! I will try to take a look at it over the weekend.

**Comment by sickdyd** [comment]
@fidellr @gignupg I fixed the issue, install the latest version and it should work as expected!

https://github.com/sickdyd/react-search-autocomplete/commit/2f2b253201529e8be8e4602548df7330b8c65192
