### ISSUE TITLE
No search results when using inputSearchString

### ISSUE THREAD

**Issue by defser** [sickdyd/react-search-autocomplete#70]
**Describe the bug**
When i use the option inputSearchString to prefill the searchbox i expect that it will display search results, i did not find a option to enable this and did try to make it word programmatically but i cannot get it to search de prefilled query

**Codesandbox example**
[Create a [codesandbox](https://codesandbox.io/) example with the problem you would like to have solved.](https://codesandbox.io/embed/icy-dust-dhi3gc?fontsize=14&hidenavigation=1&theme=dark)

**To Reproduce**
1. Go to Codesandbox example
2. Click on search javascript!
3. Search input it filled but no search results, only after i focus on it and add input then it searches...

**Expected behavior**
When inputSearchString is set at init or afterwards changed it automatically searches that input.

**Additional context**
Would be great to have it as option so the basic functionality does not change.

**Comment by defser** [comment]
It would be sufficient if there is a working workaround at this moment.

**Comment by sickdyd** [comment]
@defser Hello! Fixed in version `8.0.0`!
