### ISSUE TITLE
What is the way to check that the Search is empty after backspace clicks not by Clear?

### ISSUE THREAD

**Issue by Rahulgarg30591** [sickdyd/react-search-autocomplete#72]
Unable to trigger an event in a case when the Search String is all empty as the _onSearch_ event is not triggering on the removal of the last character.

Similar to: https://github.com/sickdyd/react-search-autocomplete/issues/17#issuecomment-831743898

I need to verify whether the textbox is empty or not as part of validation.

Thank you,

**Comment by rserafim** [comment]
Same!

**Comment by sickdyd** [comment]
@Rahulgarg30591 @rserafim Did you try with the lastest version?

I can see that `onSearch` is triggered also when the last character is removed. Check this [codesandbox](https://codesandbox.io/s/nervous-turing-24pzhs?file=/src/App.js).
