### ISSUE TITLE
Question: I would like to know how to differentiate several <ReactSearchAutocomplete /> in a single component

### ISSUE THREAD

**Issue by pedromaironi** [sickdyd/react-search-autocomplete#75]
I have several inputs inside a form. 3 of them are react-search-autocomplete. So, I had the question how I could identify each combobox. If with an id or a name...
I don't want to have to create an OnHandleSearch for <autocomplete /> that I have created on 5 or 10 forms

```
  const [state, setState] = useState({
    product: "",
    discount: 0,
    price: 0,
    tax: "",
    description: "",
    amount: 0,
    total: 0,
  });

I'm waiting for manage the autocomplete's components like this
  const handleChange = (e) => {
    setState({
      ...state,
      [e.target.name]: e.target.value,
    });
  };
```

![image](https://user-images.githubusercontent.com/43529059/176988850-b7be9cbf-468e-4485-8c32-6ec908dbc09a.png)

Thank u!

**Comment by pedromaironi** [comment]
Black:  <ReactSearchAutocomplete /> 
Blue: Simple input

**Comment by sickdyd** [comment]
Sorry, multiple search boxes in one page are not yet supported, there could be some issues.
