### ISSUE TITLE
I would like to know how create a global Styling prop for the component

### ISSUE THREAD

**Issue by pedromaironi** [sickdyd/react-search-autocomplete#76]
<ReactSearchAutocomplete
                      items={products}
                      showIcon={false}
                      onSelect={handleOnSelect}
                      autoFocus={true}
                      styling={{
                        outline: "none",
                        fontWeight: "500",
                        fontSize: "0.9rem",
                        color: "black",
                        cursor: "text",
                        backgroundColor: "white",
                        borderRadius: "5px",
                        height: "1.7rem",
                        border: "1px solid #cfd6e4",
                        width: "100%",
                      }}
                    />
I have this and I don't want to have to repeat these 9 lines in every autocomplete I create

**Comment by dankcellar** [comment]
It would be great if I could remove all style and let Bulma style it for me

**Comment by sickdyd** [comment]
@pedromaironi 

Please do not create duplicate issues, I answered this in the previous issue: https://github.com/sickdyd/react-search-autocomplete/issues/74#issuecomment-1257086542
