### ISSUE TITLE
How to customize pointer when hovering over results

### ISSUE THREAD

**Issue by agustinlaurito** [sickdyd/react-search-autocomplete#78]
Hello, im trying to customize the cursor when hovering over the results bar. I tried using cursor: pointer in the style prop but didnt worked. Anybody knows how to? This is my style object.

`const styling = {
  fontFamily: 'Poppins, sans-serif',
  fontSize: '1rem',
  height: '2.5rem',
  hoverBackgroundColor: '#eaf8bf',
  cursor: 'pointer',
  display: 'flex',
  position: 'relative',
  alignItems: 'center',
  justifyContent: 'center',
}`

**Comment by ahb10** [comment]
How did you change the cursor to pointer when hovering over results?
