### ISSUE TITLE
Search should not autoselect item from drop down list

### ISSUE THREAD

**Issue by pkgitlab** [sickdyd/react-search-autocomplete#80]
We need a search where the autosuggestion may or may not be used by user.  So we want to select nothing unless the user has clicked on a suggestion . Otherwise what the user has typed in textbox is the search term.  It seems like with the sample code when we press enter while typing something is picked from drop down list and used for search.  How can we implement the search box like we see on Google where only selected item is populated in search box. 

Thanks for this library, really appreciate the efforts!

**Comment by sickdyd** [comment]
Wow, that is definitely a bug that sneaked in somehow. Looking into it.

**Comment by sickdyd** [comment]
Fixed in the latest version!
