### ISSUE TITLE
Any way we can change the icon?

### ISSUE THREAD

**Issue by deuxailes** [sickdyd/react-search-autocomplete#84]
Title

**Comment by varsha-M-I** [comment]
You should set showIcon={false} then in formatResult you can add your desired Icons. I have created an example please refer this code sandbox example. Hope this will help !!!!

[https://codesandbox.io/s/vigorous-lake-sq2xvh?file=/src/App.js](url)

**Comment by sickdyd** [comment]
Solved by workaround, closing for now. Thanks.
