### ISSUE TITLE
Setting the maxlength on the autocomplete input

### ISSUE THREAD

**Issue by hadrian625** [sickdyd/react-search-autocomplete#87]
Would it be possible to set the maxlength property on the html input element?
This would be useful for to prevent user to type too many characters when the application would want to get the free entered text by the user as data to be saved. This would eliminate the need to have a maxlength validation

**Comment by sickdyd** [comment]
@hadrian625 Feature added in the latest version!

**Comment by sickdyd** [comment]
Forgot to update the docs: use the prop `maxLength` to define the max length of the input
