### ISSUE TITLE
How about adding classNames

### ISSUE THREAD

**Issue by Boris-Scharinger** [sickdyd/react-search-autocomplete#92]
Hi sickdyd, wonderful stuff!!
One suggestion to improve the way we can leverage (S)CSS: How about an attribute to add a className to the search input field?

**Comment by 0tii** [comment]
Went here to open exactly this issue - important feature missing

**Comment by sickdyd** [comment]
Hello guys, I added a prop to pass a class to the component, you will find it in the latest version.

A few caveats:
- in most of cases you will need to use `!important` to make the CSS work
- you will have to figure out the selector to use for your case, I added some basic examples [in the demo](https://sickdyd.github.io/react-search-autocomplete/)

**Comment by sickdyd** [comment]
I will close this as resolved. Let me know if you need more changes.
